-- Phase 6: Agent auth

-- Unique constraint on agents.name (required for ON CONFLICT upsert in sci connect)
ALTER TABLE agents ADD CONSTRAINT agents_name_unique UNIQUE (name);

-- agent_tokens: one token per connected agent
-- Token is a 32-byte random hex string, stored as SHA-256 hash (never plaintext)
CREATE TABLE agent_tokens (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  agent_id     UUID NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  token_hash   TEXT NOT NULL UNIQUE,
  token_hint   TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  expires_at   TIMESTAMPTZ
);

-- connect_requests: short-lived codes for the connect flow
CREATE TABLE connect_requests (
  id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  code        TEXT NOT NULL UNIQUE,
  agent_name  TEXT NOT NULL,
  tier        TEXT NOT NULL DEFAULT 'standard',
  profile_id  UUID REFERENCES profiles(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at  TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '10 minutes'),
  used_at     TIMESTAMPTZ
);

-- Grants
GRANT SELECT ON agent_tokens TO db_reader;
GRANT SELECT ON connect_requests TO db_reader;
GRANT SELECT, INSERT, UPDATE, DELETE ON agent_tokens TO db_writer;
GRANT SELECT, INSERT, UPDATE, DELETE ON connect_requests TO db_writer;
GRANT SELECT, INSERT, UPDATE ON agents TO db_writer;

-- NOTE: The default trusted token is generated by `sci setup` on first run.
-- Do NOT seed a hardcoded token here — that's a security issue.
-- For local dev, run: sci connect claude-code --tier trusted
