import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import { embed } from './embeddings.js'
import type { StorageAdapter } from './storage/interface.js'

const OPENROUTER_BASE = 'https://openrouter.ai/api/v1'

const DIGEST_SYSTEM = `You are a concise daily summary writer. Given a person's AI conversation messages from today, write a brief digest.

Format EXACTLY as:
## What happened today
- [bullet]
- [bullet]  (max 5 bullets)

## Key decisions
- [decision if any]

Rules: specific and factual; max 15 words per bullet; omit filler. If nothing significant happened, write one bullet: "Light activity day." Start directly with ##`

interface DigestStats {
  episodic_new: number
  semantic_promoted: number
  semantic_reinforced: number
  nodes_decayed: number
}

export interface DigestResult {
  memory_id: string | null
  markdown: string
  exported_to: string | null
}

export async function runDigestPass(
  windowStart: Date, windowEnd: Date,
  profileId: string,
  stats: DigestStats,
  apiKey: string, model: string,
  adapter: StorageAdapter
): Promise<DigestResult> {
  const dateStr = windowEnd.toISOString().slice(0, 10)

  const memories = await adapter.getEpisodicMemoriesInWindow({
    profileId, windowStart, windowEnd,
    minLength: 20, excludeDigests: true, limit: 60,
  })

  let narrative = '(No activity recorded today.)'
  if (memories.length > 0) {
    const userPrompt = memories.map((m, i) => `${i + 1}. ${m.content.slice(0, 300)}`).join('\n')
    try {
      const res = await fetch(`${OPENROUTER_BASE}/chat/completions`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://github.com/sovereign-cognitive-identity/sci',
          'X-Title': 'Sci Digest',
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: 'system', content: DIGEST_SYSTEM },
            { role: 'user', content: userPrompt },
          ],
          temperature: 0.3,
          max_tokens: 512,
        }),
      })
      if (res.ok) {
        const data = await res.json() as { choices: Array<{ message: { content: string } }> }
        narrative = data.choices[0]?.message?.content?.trim() ?? narrative
      }
    } catch (err) {
      console.error('  [digest] LLM error:', err instanceof Error ? err.message : err)
    }
  }

  const markdown = buildMarkdown(dateStr, narrative, stats)

  // Store as episodic memory
  let storedId: string | null = null
  try {
    const embedding = await embed(
      `[DIGEST ${dateStr}] ${narrative.replace(/#+\s*/g, '').replace(/\n/g, ' ').slice(0, 500)}`
    )
    const result = await adapter.storeEpisodic({
      profileId,
      content: `[DIGEST ${dateStr}] ${narrative.replace(/#+\s*/g, '').replace(/\n/g, ' ').slice(0, 500)}`,
      embedding,
      source: 'consolidation',
      metadata: { type: 'digest', date: dateStr, stats },
    })
    storedId = result.id
  } catch (err) {
    console.error('  [digest] failed to store:', err instanceof Error ? err.message : err)
  }

  const exportedTo = exportToVault(dateStr, markdown)
  return { memory_id: storedId, markdown, exported_to: exportedTo }
}

function buildMarkdown(date: string, narrative: string, stats: DigestStats): string {
  return `# Sci Digest — ${date}

${narrative}

## Memory system
- New memories: ${stats.episodic_new}
- Promoted to semantic: ${stats.semantic_promoted}
- Reinforced: ${stats.semantic_reinforced}
- Nodes decayed/flagged: ${stats.nodes_decayed}

---
*Generated by Sci nightly consolidation*
`
}

function exportToVault(date: string, markdown: string): string | null {
  const vaultPath = process.env['SCI_VAULT_PATH'] ?? `${process.env['HOME']}/Vault`
  const sciDir = join(vaultPath, 'sci', 'digests')
  try {
    if (!existsSync(sciDir)) mkdirSync(sciDir, { recursive: true })
    const filePath = join(sciDir, `${date}-digest.md`)
    writeFileSync(filePath, markdown, 'utf-8')
    return filePath
  } catch {
    return null
  }
}
